version: "3.8"

services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      -'8000:82'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.con:ro
  # php:
  # mysql:
  # composer:
  # artisan:
  # npm: